# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 23:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'Cr\xc3\xa9\xc3\xa9 le')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name=b'Modifi\xc3\xa9 le')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name=b'Cr\xc3\xa9\xc3\xa9 le')),
                ('uid', models.CharField(blank=True, db_index=True, max_length=254, null=True, unique=True, verbose_name='UID')),
                ('title', models.CharField(blank=True, max_length=254, null=True, verbose_name='Titre')),
                ('body', models.CharField(blank=True, max_length=254, null=True, verbose_name='Body Message')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Envoyee ?')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu ?')),
                ('is_email_sendable', models.BooleanField(default=False, verbose_name='A envoyer par email ?')),
                ('is_email_sent', models.BooleanField(default=False, verbose_name='Envoy\xe9e par email ?')),
                ('context_object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('context_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Receveur')),
            ],
            options={
                'ordering': ['-created_at'],
                'db_table': 'workon_notification_notification',
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
