# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workon_notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Body Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='uid',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, unique=True, verbose_name='UID'),
        ),
    ]
