# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workon_notification', '0002_auto_20160609_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='uid',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='UID'),
        ),
    ]
