# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 05:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workon_notification', '0003_auto_20160609_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.AddField(
            model_name='notification',
            name='receiver_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email receveur'),
        ),
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Sujet'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Receveur'),
        ),
    ]
