# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workon_notification', '0004_auto_20161007_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Type'),
        ),
    ]
