# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modifié le')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Adresse email')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name="Token d'activation")),
                ('is_used', models.BooleanField(default=False, verbose_name='Utilisé ?')),
                ('expiration_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="date d'expiration")),
                ('activation_date', models.DateTimeField(blank=True, null=True, verbose_name="date d'activation")),
            ],
            options={
                'verbose_name': "Clé d'activation",
                'verbose_name_plural': "Clés d'activation",
                'ordering': ('created_date', 'activation_date'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='activationtoken',
            unique_together=set([('email', 'token')]),
        ),
    ]
