# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workon_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activationtoken',
            table=None,
        ),
    ]
